branches:
  only:
  - master
language: csharp
solution: Csi.Plugins.AzureFile.sln
dotnet: 2.1.4
script:
  - dotnet build Csi.Plugins.AzureFile.sln
  - dotnet build Csi.Plugins.AzureFile.Tests.Scenarios.sln
  - dotnet test tests/Csi.Plugins.AzureFile.Tests
