apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: azurefile-csi
provisioner: csi-azurefile
reclaimPolicy: Delete
parameters:
  csiProvisionerSecretName: csi-azurefile-secret
  csiProvisionerSecretNamespace: csi-plugins-azurefile
